# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45f17c9dd989f3e00c604ebabb00fb40dfff4bd2c3484a5e3c2ac0ff48b2a1db9cf27e468b9d3681d3d536535dcc170b32694b34a619d8498827a9ffb0d633b7

test:
  secret_key_base: 9955f5848ab8a5f5c4992e9a6b35b9f52ed71e0f7502bc3cae7d4dbe550bda7ab5d506d1bd34638d8be1ff976d4ea1162950330680dbc159a773f7f02f29b51e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
